-- ============================================================
-- AniCoach Database Schema — Supabase (PostgreSQL)
-- Run this in Supabase SQL Editor: supabase.com/dashboard
-- ============================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ============================================================
-- TABLE: profiles
-- Extended user profile + game state
-- ============================================================
create table if not exists public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  username      text not null,
  avatar_color  text default '#516161',
  level         integer not null default 1,
  exp           integer not null default 0,
  streak        integer not null default 0,
  last_login    date,
  mora          integer not null default 0,
  primogems     integer not null default 0,
  -- Stats (0–100 scale)
  stat_str      integer not null default 10,
  stat_int      integer not null default 10,
  stat_vit      integer not null default 10,
  stat_agi      integer not null default 10,
  stat_chr      integer not null default 10,
  -- Timestamps
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- RLS: users can only see/edit their own profile
alter table public.profiles enable row level security;

create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

-- ============================================================
-- TABLE: activities
-- User-submitted activity logs
-- ============================================================
create table if not exists public.activities (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  title       text not null,
  description text,
  category    text not null check (category in ('olahraga','belajar','kerja','sosial','istirahat','kreatif')),
  duration    integer not null default 30,  -- minutes
  intensity   text not null default 'sedang' check (intensity in ('ringan','sedang','tinggi')),
  exp_gained  integer not null default 0,
  -- Stats boost from this activity
  boost_str   integer not null default 0,
  boost_int   integer not null default 0,
  boost_vit   integer not null default 0,
  boost_agi   integer not null default 0,
  boost_chr   integer not null default 0,
  -- Kaito's response
  kaito_dialog     text,
  kaito_expression text default 'idle',
  logged_at   timestamptz not null default now()
);

alter table public.activities enable row level security;

create policy "Users can view own activities" on public.activities
  for select using (auth.uid() = user_id);

create policy "Users can insert own activities" on public.activities
  for insert with check (auth.uid() = user_id);

-- ============================================================
-- TABLE: quests
-- Daily quests generated by Kaito AI
-- ============================================================
create table if not exists public.quests (
  id           uuid primary key default uuid_generate_v4(),
  user_id      uuid not null references public.profiles(id) on delete cascade,
  title        text not null,
  description  text,
  category     text,
  exp_reward   integer not null default 100,
  difficulty   text not null default 'sedang' check (difficulty in ('ringan','sedang','epik')),
  status       text not null default 'active' check (status in ('active','completed','failed','expired')),
  generated_at date not null default current_date,
  completed_at timestamptz
);

alter table public.quests enable row level security;

create policy "Users can view own quests" on public.quests
  for select using (auth.uid() = user_id);

create policy "Users can insert own quests" on public.quests
  for insert with check (auth.uid() = user_id);

create policy "Users can update own quests" on public.quests
  for update using (auth.uid() = user_id);

-- ============================================================
-- TABLE: achievements
-- Badges and achievement unlocks
-- ============================================================
create table if not exists public.achievements (
  id           uuid primary key default uuid_generate_v4(),
  user_id      uuid not null references public.profiles(id) on delete cascade,
  badge_key    text not null,  -- e.g. 'first_quest', 'streak_7', 'level_10'
  badge_name   text not null,
  badge_icon   text not null,
  unlocked_at  timestamptz not null default now(),
  unique (user_id, badge_key)
);

alter table public.achievements enable row level security;

create policy "Users can view own achievements" on public.achievements
  for select using (auth.uid() = user_id);

create policy "Users can insert own achievements" on public.achievements
  for insert with check (auth.uid() = user_id);

-- ============================================================
-- TABLE: leaderboard_weekly
-- Cached weekly snapshot — recalculated via edge function
-- ============================================================
create table if not exists public.leaderboard_weekly (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  username    text not null,
  level       integer not null,
  exp_week    integer not null default 0,  -- EXP gained this week
  rank        integer,
  week_start  date not null,
  unique (user_id, week_start)
);

alter table public.leaderboard_weekly enable row level security;

create policy "Anyone can view leaderboard" on public.leaderboard_weekly
  for select using (true);

-- ============================================================
-- FUNCTION: handle_new_user
-- Auto-create profile on signup
-- ============================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

-- Trigger on auth.users insert
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ============================================================
-- FUNCTION: update_updated_at
-- Auto-update timestamp
-- ============================================================
create or replace function public.update_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_updated_at
  before update on public.profiles
  for each row execute procedure public.update_updated_at();
